#!/usr/bin/env bash

e_header "Installing binaries via homebrew ..."
brew_install_or_upgrade "ack"
brew_install_or_upgrade "apple-gcc42"
brew_install_or_upgrade "autoconf"
brew_install_or_upgrade "autojump"
brew_install_or_upgrade "automake"
brew_install_or_upgrade "bash" # Install Bash 4
brew_install_or_upgrade "boot2docker"
brew_install_or_upgrade "cairo"
brew_install_or_upgrade "coreutils" # Install GNU core utilities (those that come with OS X are outdated)
brew_install_or_upgrade "cscope"
brew_install_or_upgrade "ctags"
brew_install_or_upgrade "docker"
brew_install_or_upgrade "dnsmasq"
brew_install_or_upgrade "emacs"
brew_install_or_upgrade "fasd"
brew_install_or_upgrade "ffmpeg"
brew_install_or_upgrade "fig"
brew_install_or_upgrade "findutils" # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew_install_or_upgrade "fontconfig"
brew_install_or_upgrade "freetype"
brew_install_or_upgrade "fswatch"
brew_install_or_upgrade "gdbm"
brew_install_or_upgrade "git"
brew_install_or_upgrade "glib"
brew_install_or_upgrade "go"
brew_install_or_upgrade "graphicsmagick"
brew_install_or_upgrade "homebrew/dupes/grep"
brew_install_or_upgrade "htop-osx"
brew_install_or_upgrade "httpie"
brew_install_or_upgrade "httrack"
brew_install_or_upgrade "hub"
brew_install_or_upgrade "icu4c" #International Components for Unicode
brew_install_or_upgrade 'imagemagick'
brew_install_or_upgrade "ios-sim"
brew_install_or_upgrade "irssi"
brew_install_or_upgrade "kdiff3"
brew_install_or_upgrade "libevent"
brew_install_or_upgrade "libpng"
brew_install_or_upgrade "libsodium"
brew_install_or_upgrade "mackup"
brew_install_or_upgrade "macvim"
brew_install_or_upgrade "mobile-shell"
brew_install_or_upgrade "ngrep"
brew_install_or_upgrade "ngrok"
brew_install_or_upgrade "node"
brew_install_or_upgrade "openssl"
brew_install_or_upgrade "pv"
brew_install_or_upgrade "python"
brew_install_or_upgrade 'qt'
brew_install_or_upgrade "readline"
brew_install_or_upgrade "realpath"
brew_install_or_upgrade "rename"
brew_install_or_upgrade "rbenv"
brew_install_or_upgrade "ruby"
brew_install_or_upgrade 'ruby-build'
brew_install_or_upgrade "rsync"
brew_install_or_upgrade "saltstack"
brew_install_or_upgrade "sqlite"
brew_install_or_upgrade "ssh-copy-id"
brew_install_or_upgrade "subversion"
brew_install_or_upgrade "swig"
brew_install_or_upgrade "sshfs"
brew_install_or_upgrade "tig"
brew_install_or_upgrade "trash"
brew_install_or_upgrade "tree"
brew_install_or_upgrade "webkit2png"
brew_install_or_upgrade "wget"
brew_install_or_upgrade "zopfli"
# brew_install_or_upgrade "zeromq"
brew_install_or_upgrade 'zsh'
brew_install_or_upgrade "zsh-completions"
brew_install_or_upgrade "zsh-syntax-highlighting"